---
- name: Actualizar repositorios adaptando el locale a inglés o español
  hosts: all
  become: yes
  become_user: root
  tasks:

    - name: Actualizar repositorios usando el locale detectado
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"