---
- name: UpdateRepos
  hosts: all
  become: yes
  tasks:

    - name: Check and update repos
      ansible.builtin.apt:
        update_cache: true
        autoremove: true
        autoclean: true
